// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnpMQQXmRpN0n84snPwITlZiMOPTCcf7c',
    appId: '1:901813966016:web:190654837dd59c5f4dc925',
    messagingSenderId: '901813966016',
    projectId: 'todopage-a3ec3',
    authDomain: 'todopage-a3ec3.firebaseapp.com',
    storageBucket: 'todopage-a3ec3.firebasestorage.app',
    measurementId: 'G-PVT8MM0LE6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4sZN4_7GZzMFhd359DBM_awPvQY1YkMI',
    appId: '1:901813966016:android:7d8782517a679ecc4dc925',
    messagingSenderId: '901813966016',
    projectId: 'todopage-a3ec3',
    storageBucket: 'todopage-a3ec3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCevDrwdz3baeZd5sX3OGVPM6NkRd_GdFE',
    appId: '1:901813966016:ios:d7e90ba24265c1264dc925',
    messagingSenderId: '901813966016',
    projectId: 'todopage-a3ec3',
    storageBucket: 'todopage-a3ec3.firebasestorage.app',
    iosBundleId: 'com.example.todopage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCevDrwdz3baeZd5sX3OGVPM6NkRd_GdFE',
    appId: '1:901813966016:ios:d7e90ba24265c1264dc925',
    messagingSenderId: '901813966016',
    projectId: 'todopage-a3ec3',
    storageBucket: 'todopage-a3ec3.firebasestorage.app',
    iosBundleId: 'com.example.todopage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnpMQQXmRpN0n84snPwITlZiMOPTCcf7c',
    appId: '1:901813966016:web:ee94d90bcbf5f1644dc925',
    messagingSenderId: '901813966016',
    projectId: 'todopage-a3ec3',
    authDomain: 'todopage-a3ec3.firebaseapp.com',
    storageBucket: 'todopage-a3ec3.firebasestorage.app',
    measurementId: 'G-2FCMGG9SPD',
  );
}
